spring:
  data:
    redis:
      host: redis-16721.c294.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 16721
      username: default
      password: wvVU7YjbPSQ5LftdiOk6NXXBdf5MBmFS

  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always